package co.edu.ude.poo.procesospoliticos.vistas.gui;

import co.edu.ude.poo.procesospoliticos.modelo.entidades.ComunaModel;
import co.edu.ude.poo.procesospoliticos.modelo.crud.ComunaModelJpaController;
import co.edu.ude.poo.procesospoliticos.modelo.entidades.LocalvotacionModel;
import co.edu.ude.poo.procesospoliticos.modelo.crud.LocalvotacionModelJpaController;

import java.awt.Toolkit;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 * @author camilo castellar
 */
public class VentanaLocalVotacion extends javax.swing.JDialog {

    EntityManagerFactory con = Persistence.createEntityManagerFactory("ProcesosPoliticosPU");
    LocalvotacionModelJpaController localvotacionCrud = new LocalvotacionModelJpaController(con);
    
    public VentanaLocalVotacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarComunas();
    }

    public void habilitarBotones(boolean agregar, boolean buscar, boolean modificar, boolean eliminar) {
        btnAgregarLocalVotacion.setEnabled(agregar);
        btnBuscarLocalVotacion.setEnabled(buscar);
        btnModificarLocalVotacion.setEnabled(modificar);
        btnEliminarLocalVotacion.setEnabled(eliminar);
    }

    public void cargarComunas() {
        
        ComunaModelJpaController comunaCrud = new ComunaModelJpaController(con);
        ComunaModel comunaModel = new ComunaModel();

        cmbComunaLocal.removeAllItems();
        cmbComunaLocal.addItem("Seleccione una comuna");
        for (ComunaModel c : comunaCrud.findComunaModelEntities()) {
            cmbComunaLocal.addItem(c.getNombre());
        }

        cmbComunaLocal.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIDLocalVotacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLocalVotacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbComunaLocal = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarLocalVotacion = new javax.swing.JButton();
        btnBuscarLocalVotacion = new javax.swing.JButton();
        btnModificarLocalVotacion = new javax.swing.JButton();
        btnEliminarLocalVotacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procesos Politícos - Gestión de Locales de Votación");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Datos del local de votación:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID:");

        txtIDLocalVotacion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtIDLocalVotacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDLocalVotacionKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre de comuna:");

        txtLocalVotacion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Local de votación");

        cmbComunaLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtIDLocalVotacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLocalVotacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbComunaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDLocalVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbComunaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3});

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO PARA GESTIONAR LOCALES DE VOTACIÓN");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/Location-icon.png"))); // NOI18N

        btnAgregarLocalVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        btnAgregarLocalVotacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAgregarLocalVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLocalVotacionActionPerformed(evt);
            }
        });

        btnBuscarLocalVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        btnBuscarLocalVotacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBuscarLocalVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLocalVotacionActionPerformed(evt);
            }
        });

        btnModificarLocalVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        btnModificarLocalVotacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnModificarLocalVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarLocalVotacionActionPerformed(evt);
            }
        });

        btnEliminarLocalVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        btnEliminarLocalVotacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminarLocalVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLocalVotacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminarLocalVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarLocalVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarLocalVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarLocalVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarLocalVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarLocalVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarLocalVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarLocalVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarLocalVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLocalVotacionActionPerformed
        // Datos de formulario
        String id = txtIDLocalVotacion.getText();

        // Validar que no este vacio
        if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el id del local", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtIDLocalVotacion.setText("");
            txtIDLocalVotacion.requestFocus();
            return;
        }  

        String localVotacion = txtLocalVotacion.getText();

        // Validar que no este vacio 
        if (localVotacion == null || localVotacion.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la ubicación del local", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLocalVotacion.setText("");
            txtLocalVotacion.requestFocus();
            return;
        }

        // Validar que el combobox tenga una comuna seleccionada
        if (cmbComunaLocal.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comuna", "ERROR", JOptionPane.ERROR_MESSAGE);
            cmbComunaLocal.requestFocus();
            return;
        }

        String nombreComuna = cmbComunaLocal.getSelectedItem().toString();

        // obtener el id con el nombre de la comuna seleccionada para luego asignarla al objeto LocalVotacion
        // EntityManagerFactory con = Persistence.createEntityManagerFactory("ProcesosPoliticosPU");
        ComunaModelJpaController comunaCrud = new ComunaModelJpaController(con);
        ComunaModel comunaModel = new ComunaModel();
        String idComuna = "";
        for (ComunaModel c : comunaCrud.findComunaModelEntities()) {
            if (c.getNombre().equals(nombreComuna)) {
                idComuna = c.getId().toString();
            }
        }
        ComunaModel comuna = comunaCrud.findComunaModel(Integer.parseInt(idComuna));

        // Crear objeto LocalVotacion
        LocalvotacionModel l = new LocalvotacionModel();
        l.setUbicacion(localVotacion);
        l.setComuna(comuna);
        
        try {
            localvotacionCrud.create(l);
            // Mensaje de confirmacion
            int totalLocalesAlmacenados = localvotacionCrud.getLocalvotacionModelCount();
            String msg = "La ubicación del local de votación, se guardo con éxito";
            msg += "\n" + " TOTAL: " + totalLocalesAlmacenados;
            JOptionPane.showMessageDialog(this, msg, "RESULTADO", JOptionPane.WARNING_MESSAGE); 
            txtIDLocalVotacion.setText("");          
            cmbComunaLocal.setSelectedIndex(0);
            txtLocalVotacion.setText("");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarLocalVotacionActionPerformed

    private void txtIDLocalVotacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDLocalVotacionKeyTyped
        // validar que el ID sea Integer
        char tecla = evt.getKeyChar();
        if(!Character.isDigit(tecla)) { 
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtIDLocalVotacionKeyTyped

    private void btnBuscarLocalVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLocalVotacionActionPerformed
        String id = txtIDLocalVotacion.getText();

        // Validar que no este vacio
        if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el id del local", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtIDLocalVotacion.setText("");
            txtIDLocalVotacion.requestFocus();
            return;
        }

        // validar que el contenga la llave a buscar
        if (localvotacionCrud.findLocalvotacionModel(Integer.parseInt(id)) == null) {
            JOptionPane.showMessageDialog(this, "El local con ID: " + id + " no existe", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //recupera el objeto para mostrarlo en los campos del formulario
        LocalvotacionModel l = localvotacionCrud.findLocalvotacionModel(Integer.parseInt(id));
        txtLocalVotacion.setText(l.getUbicacion());
        cmbComunaLocal.setSelectedItem(l.getComuna().getNombre());
        
        // habilitar botones, y deshabilitar el boton agregar
        habilitarBotones(false, true, true, true);
    }//GEN-LAST:event_btnBuscarLocalVotacionActionPerformed

    private void btnModificarLocalVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLocalVotacionActionPerformed
        String id = txtIDLocalVotacion.getText();

        // Validar que no este vacio
        if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el id del local", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtIDLocalVotacion.setText("");
            txtIDLocalVotacion.requestFocus();
            return;
        }

        // validar que el contenga la llave a buscar
        if (localvotacionCrud.findLocalvotacionModel(Integer.parseInt(id)) == null) {
            JOptionPane.showMessageDialog(this, "El local con ID: " + id + " no existe", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validar que el combobox tenga una comuna seleccionada
        if (cmbComunaLocal.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comuna", "ERROR", JOptionPane.ERROR_MESSAGE);
            cmbComunaLocal.requestFocus();
            return;
        }
        
        String localVotacion = txtLocalVotacion.getText();
        // Validar que no este vacio
        if (localVotacion == null || localVotacion.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la ubicación", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtIDLocalVotacion.setText("");
            txtIDLocalVotacion.requestFocus();
            return;
        }

        String nombreComuna = cmbComunaLocal.getSelectedItem().toString();

        // obtener el id con el nombre de la comuna seleccionada para luego asignarla al objeto LocalVotacion
        // EntityManagerFactory con = Persistence.createEntityManagerFactory("ProcesosPoliticosPU");
        ComunaModelJpaController comunaCrud = new ComunaModelJpaController(con);
        ComunaModel comunaModel = new ComunaModel();

        String idComuna = "";

        for (ComunaModel c : comunaCrud.findComunaModelEntities()) {
            if (c.getNombre().equals(nombreComuna)) {
                idComuna = c.getId().toString();
            }
        }
        
        ComunaModel comuna = comunaCrud.findComunaModel(Integer.parseInt(idComuna));

        // onbtener el objeto LocalVotacion
        LocalvotacionModel l = localvotacionCrud.findLocalvotacionModel(Integer.parseInt(id));
        l.setUbicacion(localVotacion);
        l.setComuna(comuna);

        try {
            localvotacionCrud.edit(l);
            JOptionPane.showMessageDialog(this, "La comuna con ID: " + id + " se actualizo con éxito", "RESULTADO", JOptionPane.WARNING_MESSAGE);
            txtIDLocalVotacion.setText("");
            cmbComunaLocal.setSelectedIndex(0);
            txtLocalVotacion.setText("");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnModificarLocalVotacionActionPerformed

    private void btnEliminarLocalVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComunaActionPerformed
        String id = txtIDLocalVotacion.getText();

        // Validar que no este vacio
        if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el id del local de votación", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtIDLocalVotacion.setText("");
            txtIDLocalVotacion.requestFocus();
            return;
        }

        // validar que el contenga la llave a buscar
        if (localvotacionCrud.findLocalvotacionModel(Integer.parseInt(id)) == null) {
            JOptionPane.showMessageDialog(this, "El local de votación con ID: " + id + " no existe", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar la ubicación con ID: " + id + "?", "CONFIRMACION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE); 
        
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                localvotacionCrud.destroy(Integer.parseInt(id));
                JOptionPane.showMessageDialog(this, "El local de votación con ID: " + id + " se elimino con éxito", "RESULTADO", JOptionPane.WARNING_MESSAGE);
                txtIDLocalVotacion.setText("");
                cmbComunaLocal.setSelectedIndex(0);
                txtLocalVotacion.setText("");
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarComunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLocalVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLocalVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLocalVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLocalVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaLocalVotacion dialog = new VentanaLocalVotacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLocalVotacion;
    private javax.swing.JButton btnBuscarLocalVotacion;
    private javax.swing.JButton btnEliminarLocalVotacion;
    private javax.swing.JButton btnModificarLocalVotacion;
    private javax.swing.JComboBox<String> cmbComunaLocal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIDLocalVotacion;
    private javax.swing.JTextField txtLocalVotacion;
    // End of variables declaration//GEN-END:variables
}
