/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.ude.poo.procesospoliticos.vistas.gui;

/**
 *
 * @author camilo castellar
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenu = new javax.swing.JMenuBar();
        menuPartido = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        menuComuna = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        menuLocalVotacion = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        menuCiudadano = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        menuApoderadoMesa = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        menuCandidato = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        menuVocalMesa = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        menuMesa = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        menuVoto = new javax.swing.JMenu();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem45 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPartido.setText("Partido");

        jMenuItem1.setText("Agregar Partido...");
        menuPartido.add(jMenuItem1);

        jMenuItem2.setText("Buscar Partido...");
        menuPartido.add(jMenuItem2);

        jMenuItem3.setText("Modificar Partido...");
        menuPartido.add(jMenuItem3);

        jMenuItem4.setText("Eliminar Partido...");
        menuPartido.add(jMenuItem4);

        jMenu2.setText("Reportes");

        jMenuItem22.setText("Listar Todo...");
        jMenu2.add(jMenuItem22);

        menuPartido.add(jMenu2);

        BarraMenu.add(menuPartido);

        menuComuna.setText("Comuna");

        jMenuItem5.setText("Agregar Comuna...");
        menuComuna.add(jMenuItem5);

        jMenuItem6.setText("Buscar Comuna...");
        menuComuna.add(jMenuItem6);

        jMenuItem7.setText("Modificar Comuna...");
        menuComuna.add(jMenuItem7);

        jMenuItem8.setText("Eliminar Comuna...");
        menuComuna.add(jMenuItem8);

        jMenu3.setText("Reportes");

        jMenuItem23.setText("Listar Todo...");
        jMenu3.add(jMenuItem23);

        menuComuna.add(jMenu3);

        BarraMenu.add(menuComuna);

        menuLocalVotacion.setText("Local Votación");

        jMenuItem9.setText("Agregar Local Votación...");
        menuLocalVotacion.add(jMenuItem9);

        jMenuItem10.setText("Buscar Local Votación...");
        menuLocalVotacion.add(jMenuItem10);

        jMenuItem11.setText("Modificar Local Votación...");
        menuLocalVotacion.add(jMenuItem11);

        jMenuItem12.setText("Eliminar Local Votación...");
        menuLocalVotacion.add(jMenuItem12);

        jMenu4.setText("Reportes");

        jMenuItem24.setText("Listar Todo..");
        jMenu4.add(jMenuItem24);

        menuLocalVotacion.add(jMenu4);

        BarraMenu.add(menuLocalVotacion);

        menuCiudadano.setText("Ciudadano");

        jMenuItem13.setText("Agregar Ciudadano...");
        menuCiudadano.add(jMenuItem13);

        jMenuItem14.setText("Buscar CIudadano...");
        menuCiudadano.add(jMenuItem14);

        jMenuItem15.setText("Modificar Ciudadano...");
        menuCiudadano.add(jMenuItem15);

        jMenuItem16.setText("Eliminar Ciudadano...");
        menuCiudadano.add(jMenuItem16);

        jMenu5.setText("Reportes");

        jMenuItem25.setText("Listar Todo...");
        jMenu5.add(jMenuItem25);

        menuCiudadano.add(jMenu5);

        BarraMenu.add(menuCiudadano);

        menuApoderadoMesa.setText("Apoderado de Mesa");

        jMenuItem17.setText("Agregar Apoderado...");
        menuApoderadoMesa.add(jMenuItem17);

        jMenuItem18.setText("Buscar Apoderado...");
        menuApoderadoMesa.add(jMenuItem18);

        jMenuItem19.setText("Modificar Apoderado...");
        menuApoderadoMesa.add(jMenuItem19);

        jMenuItem20.setText("Eliminar Apoderado...");
        menuApoderadoMesa.add(jMenuItem20);

        jMenu1.setText("Reportes");

        jMenuItem21.setText("Listar Todo...");
        jMenu1.add(jMenuItem21);

        menuApoderadoMesa.add(jMenu1);

        BarraMenu.add(menuApoderadoMesa);

        menuCandidato.setText("Candidato");

        jMenuItem26.setText("Agregar Candidato...");
        menuCandidato.add(jMenuItem26);

        jMenuItem27.setText("Buscar Candidato...");
        menuCandidato.add(jMenuItem27);

        jMenuItem28.setText("Modificar Candidato...");
        menuCandidato.add(jMenuItem28);

        jMenuItem29.setText("Elimiinar Candidato...");
        menuCandidato.add(jMenuItem29);

        jMenu6.setText("Reportes");

        jMenuItem30.setText("Listar Todo...");
        jMenu6.add(jMenuItem30);

        menuCandidato.add(jMenu6);

        BarraMenu.add(menuCandidato);

        menuVocalMesa.setText("Vocal de Mesa");

        jMenuItem31.setText("Agregar Vocal Mesa...");
        menuVocalMesa.add(jMenuItem31);

        jMenuItem32.setText("Buscar Vocal Mesa...");
        menuVocalMesa.add(jMenuItem32);

        jMenuItem33.setText("Modificar Vocal Mesa...");
        menuVocalMesa.add(jMenuItem33);

        jMenuItem34.setText("Eliminar Vocal Mesa...");
        menuVocalMesa.add(jMenuItem34);

        jMenu7.setText("Reportes");

        jMenuItem35.setText("Listar Todo...");
        jMenu7.add(jMenuItem35);

        menuVocalMesa.add(jMenu7);

        BarraMenu.add(menuVocalMesa);

        menuMesa.setText("Mesa");

        jMenuItem36.setText("Agregar Mesa...");
        menuMesa.add(jMenuItem36);

        jMenuItem37.setText("Buscar Mesa...");
        menuMesa.add(jMenuItem37);

        jMenuItem38.setText("Modificar Mesa...");
        menuMesa.add(jMenuItem38);

        jMenuItem39.setText("Eliminar Mesa...");
        menuMesa.add(jMenuItem39);

        jMenu8.setText("Reportes");

        jMenuItem40.setText("Listar Todo...");
        jMenu8.add(jMenuItem40);

        menuMesa.add(jMenu8);

        BarraMenu.add(menuMesa);

        menuVoto.setText("Voto");

        jMenuItem41.setText("Agregar Voto...");
        menuVoto.add(jMenuItem41);

        jMenuItem42.setText("Buscar Voto...");
        menuVoto.add(jMenuItem42);

        jMenuItem43.setText("Modificar Voto...");
        menuVoto.add(jMenuItem43);

        jMenuItem44.setText("Eliminar Voto...");
        menuVoto.add(jMenuItem44);

        jMenu9.setText("Reportes");

        jMenuItem45.setText("Listar Todo...");
        jMenu9.add(jMenuItem45);

        menuVoto.add(jMenu9);

        BarraMenu.add(menuVoto);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuApoderadoMesa;
    private javax.swing.JMenu menuCandidato;
    private javax.swing.JMenu menuCiudadano;
    private javax.swing.JMenu menuComuna;
    private javax.swing.JMenu menuLocalVotacion;
    private javax.swing.JMenu menuMesa;
    private javax.swing.JMenu menuPartido;
    private javax.swing.JMenu menuVocalMesa;
    private javax.swing.JMenu menuVoto;
    // End of variables declaration//GEN-END:variables
}
