package co.edu.ude.poo.procesospoliticos.vistas.gui;

/**
 * @author camilo castellar
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        menuPartido = new javax.swing.JMenu();
        itemAgregarPartido = new javax.swing.JMenuItem();
        itemBuscarPartido = new javax.swing.JMenuItem();
        itemModificarPartido = new javax.swing.JMenuItem();
        itemEliminarPartido = new javax.swing.JMenuItem();
        submenuPartido = new javax.swing.JMenu();
        itemListarPartido = new javax.swing.JMenuItem();
        menuComuna = new javax.swing.JMenu();
        itemAgregarComuna = new javax.swing.JMenuItem();
        itemBuscarComuna = new javax.swing.JMenuItem();
        itemModiificarComuna = new javax.swing.JMenuItem();
        itemEliminarComuna = new javax.swing.JMenuItem();
        submenuComuna = new javax.swing.JMenu();
        itemListarComuna = new javax.swing.JMenuItem();
        menuLocalVotacion = new javax.swing.JMenu();
        itemAgregarLocalVotacion = new javax.swing.JMenuItem();
        itemBuscarLocalVotacion = new javax.swing.JMenuItem();
        itemModificarLocalVotacion = new javax.swing.JMenuItem();
        itemEliminarLocalVotacion = new javax.swing.JMenuItem();
        submenuLocalVotacion = new javax.swing.JMenu();
        itemLIstarLocalVotacion = new javax.swing.JMenuItem();
        menuCiudadano = new javax.swing.JMenu();
        itemAgregarCiudadano = new javax.swing.JMenuItem();
        itemBuscarCiudadano = new javax.swing.JMenuItem();
        itemModificarCiudadano = new javax.swing.JMenuItem();
        itemEliminarCiudadano = new javax.swing.JMenuItem();
        submenuCiudadano = new javax.swing.JMenu();
        itemListarCiudadano = new javax.swing.JMenuItem();
        menuApoderadoMesa = new javax.swing.JMenu();
        itemAgregarApoderado = new javax.swing.JMenuItem();
        itemBuscarApoderado = new javax.swing.JMenuItem();
        itemModificarApoderado = new javax.swing.JMenuItem();
        itemEliminarApoderado = new javax.swing.JMenuItem();
        submenuApoderado = new javax.swing.JMenu();
        itemListarApoderado = new javax.swing.JMenuItem();
        menuCandidato = new javax.swing.JMenu();
        itemAgregarCandidato = new javax.swing.JMenuItem();
        itemBuscarCandidato = new javax.swing.JMenuItem();
        itemModificarCandidato = new javax.swing.JMenuItem();
        itemEliminarCandidato = new javax.swing.JMenuItem();
        submenuCandidato = new javax.swing.JMenu();
        itemListarCandidato = new javax.swing.JMenuItem();
        menuVocalMesa = new javax.swing.JMenu();
        itemAgregarVocal = new javax.swing.JMenuItem();
        itemBuscarVocal = new javax.swing.JMenuItem();
        itemModificarVocal = new javax.swing.JMenuItem();
        itemEliminarVocal = new javax.swing.JMenuItem();
        submenuVocal = new javax.swing.JMenu();
        itemListarVocal = new javax.swing.JMenuItem();
        menuMesa = new javax.swing.JMenu();
        itemAgregarMesa = new javax.swing.JMenuItem();
        itemBuscarMesa = new javax.swing.JMenuItem();
        itemModificarMesa = new javax.swing.JMenuItem();
        itemEliminarMesa = new javax.swing.JMenuItem();
        submenuMesa = new javax.swing.JMenu();
        itemListarMesa = new javax.swing.JMenuItem();
        menuVoto = new javax.swing.JMenu();
        itemAgregarVoto = new javax.swing.JMenuItem();
        itemBuscarVoto = new javax.swing.JMenuItem();
        itemModificarVoto = new javax.swing.JMenuItem();
        itemEliminarVoto = new javax.swing.JMenuItem();
        submenuVoto = new javax.swing.JMenu();
        itemListarVoto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Procesos Politícos");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/wave.png"))); // NOI18N

        menuPartido.setText("Partido");

        itemAgregarPartido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        itemAgregarPartido.setText("Agregar Partido...");
        itemAgregarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarPartidoActionPerformed(evt);
            }
        });
        menuPartido.add(itemAgregarPartido);

        itemBuscarPartido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        itemBuscarPartido.setText("Buscar Partido...");
        itemBuscarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarPartidoActionPerformed(evt);
            }
        });
        menuPartido.add(itemBuscarPartido);

        itemModificarPartido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        itemModificarPartido.setText("Modificar Partido...");
        itemModificarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarPartidoActionPerformed(evt);
            }
        });
        menuPartido.add(itemModificarPartido);

        itemEliminarPartido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        itemEliminarPartido.setText("Eliminar Partido...");
        itemEliminarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarPartidoActionPerformed(evt);
            }
        });
        menuPartido.add(itemEliminarPartido);

        submenuPartido.setText("Reportes");

        itemListarPartido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/list-icon.png"))); // NOI18N
        itemListarPartido.setText("Listar Todo...");
        submenuPartido.add(itemListarPartido);

        menuPartido.add(submenuPartido);

        BarraMenu.add(menuPartido);

        menuComuna.setText("Comuna");

        itemAgregarComuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        itemAgregarComuna.setText("Agregar Comuna...");
        itemAgregarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarComunaActionPerformed(evt);
            }
        });
        menuComuna.add(itemAgregarComuna);

        itemBuscarComuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        itemBuscarComuna.setText("Buscar Comuna...");
        itemBuscarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarComunaActionPerformed(evt);
            }
        });
        menuComuna.add(itemBuscarComuna);

        itemModiificarComuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        itemModiificarComuna.setText("Modificar Comuna...");
        itemModiificarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModiificarComunaActionPerformed(evt);
            }
        });
        menuComuna.add(itemModiificarComuna);

        itemEliminarComuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        itemEliminarComuna.setText("Eliminar Comuna...");
        itemEliminarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarComunaActionPerformed(evt);
            }
        });
        menuComuna.add(itemEliminarComuna);

        submenuComuna.setText("Reportes");

        itemListarComuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/list-icon.png"))); // NOI18N
        itemListarComuna.setText("Listar Todo...");
        submenuComuna.add(itemListarComuna);

        menuComuna.add(submenuComuna);

        BarraMenu.add(menuComuna);

        menuLocalVotacion.setText("Local Votación");

        itemAgregarLocalVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        itemAgregarLocalVotacion.setText("Agregar Local Votación...");
        itemAgregarLocalVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarLocalVotacionActionPerformed(evt);
            }
        });
        menuLocalVotacion.add(itemAgregarLocalVotacion);

        itemBuscarLocalVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        itemBuscarLocalVotacion.setText("Buscar Local Votación...");
        itemBuscarLocalVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarLocalVotacionActionPerformed(evt);
            }
        });
        menuLocalVotacion.add(itemBuscarLocalVotacion);

        itemModificarLocalVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        itemModificarLocalVotacion.setText("Modificar Local Votación...");
        itemModificarLocalVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarLocalVotacionActionPerformed(evt);
            }
        });
        menuLocalVotacion.add(itemModificarLocalVotacion);

        itemEliminarLocalVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        itemEliminarLocalVotacion.setText("Eliminar Local Votación...");
        itemEliminarLocalVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarLocalVotacionActionPerformed(evt);
            }
        });
        menuLocalVotacion.add(itemEliminarLocalVotacion);

        submenuLocalVotacion.setText("Reportes");

        itemLIstarLocalVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/list-icon.png"))); // NOI18N
        itemLIstarLocalVotacion.setText("Listar Todo..");
        submenuLocalVotacion.add(itemLIstarLocalVotacion);

        menuLocalVotacion.add(submenuLocalVotacion);

        BarraMenu.add(menuLocalVotacion);

        menuCiudadano.setText("Ciudadano");

        itemAgregarCiudadano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        itemAgregarCiudadano.setText("Agregar Ciudadano...");
        itemAgregarCiudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarCiudadanoActionPerformed(evt);
            }
        });
        menuCiudadano.add(itemAgregarCiudadano);

        itemBuscarCiudadano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        itemBuscarCiudadano.setText("Buscar CIudadano...");
        itemBuscarCiudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarCiudadanoActionPerformed(evt);
            }
        });
        menuCiudadano.add(itemBuscarCiudadano);

        itemModificarCiudadano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        itemModificarCiudadano.setText("Modificar Ciudadano...");
        itemModificarCiudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarCiudadanoActionPerformed(evt);
            }
        });
        menuCiudadano.add(itemModificarCiudadano);

        itemEliminarCiudadano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        itemEliminarCiudadano.setText("Eliminar Ciudadano...");
        itemEliminarCiudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarCiudadanoActionPerformed(evt);
            }
        });
        menuCiudadano.add(itemEliminarCiudadano);

        submenuCiudadano.setText("Reportes");

        itemListarCiudadano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/list-icon.png"))); // NOI18N
        itemListarCiudadano.setText("Listar Todo...");
        submenuCiudadano.add(itemListarCiudadano);

        menuCiudadano.add(submenuCiudadano);

        BarraMenu.add(menuCiudadano);

        menuApoderadoMesa.setText("Apoderado de Mesa");

        itemAgregarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        itemAgregarApoderado.setText("Agregar Apoderado...");
        menuApoderadoMesa.add(itemAgregarApoderado);

        itemBuscarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        itemBuscarApoderado.setText("Buscar Apoderado...");
        menuApoderadoMesa.add(itemBuscarApoderado);

        itemModificarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        itemModificarApoderado.setText("Modificar Apoderado...");
        menuApoderadoMesa.add(itemModificarApoderado);

        itemEliminarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        itemEliminarApoderado.setText("Eliminar Apoderado...");
        menuApoderadoMesa.add(itemEliminarApoderado);

        submenuApoderado.setText("Reportes");

        itemListarApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/list-icon.png"))); // NOI18N
        itemListarApoderado.setText("Listar Todo...");
        submenuApoderado.add(itemListarApoderado);

        menuApoderadoMesa.add(submenuApoderado);

        BarraMenu.add(menuApoderadoMesa);

        menuCandidato.setText("Candidato");

        itemAgregarCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        itemAgregarCandidato.setText("Agregar Candidato...");
        menuCandidato.add(itemAgregarCandidato);

        itemBuscarCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        itemBuscarCandidato.setText("Buscar Candidato...");
        menuCandidato.add(itemBuscarCandidato);

        itemModificarCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        itemModificarCandidato.setText("Modificar Candidato...");
        menuCandidato.add(itemModificarCandidato);

        itemEliminarCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        itemEliminarCandidato.setText("Elimiinar Candidato...");
        menuCandidato.add(itemEliminarCandidato);

        submenuCandidato.setText("Reportes");

        itemListarCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/list-icon.png"))); // NOI18N
        itemListarCandidato.setText("Listar Todo...");
        submenuCandidato.add(itemListarCandidato);

        menuCandidato.add(submenuCandidato);

        BarraMenu.add(menuCandidato);

        menuVocalMesa.setText("Vocal de Mesa");

        itemAgregarVocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        itemAgregarVocal.setText("Agregar Vocal Mesa...");
        menuVocalMesa.add(itemAgregarVocal);

        itemBuscarVocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        itemBuscarVocal.setText("Buscar Vocal Mesa...");
        menuVocalMesa.add(itemBuscarVocal);

        itemModificarVocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        itemModificarVocal.setText("Modificar Vocal Mesa...");
        menuVocalMesa.add(itemModificarVocal);

        itemEliminarVocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        itemEliminarVocal.setText("Eliminar Vocal Mesa...");
        menuVocalMesa.add(itemEliminarVocal);

        submenuVocal.setText("Reportes");

        itemListarVocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/list-icon.png"))); // NOI18N
        itemListarVocal.setText("Listar Todo...");
        submenuVocal.add(itemListarVocal);

        menuVocalMesa.add(submenuVocal);

        BarraMenu.add(menuVocalMesa);

        menuMesa.setText("Mesa de Votación");

        itemAgregarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        itemAgregarMesa.setText("Agregar Mesa...");
        menuMesa.add(itemAgregarMesa);

        itemBuscarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        itemBuscarMesa.setText("Buscar Mesa...");
        menuMesa.add(itemBuscarMesa);

        itemModificarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        itemModificarMesa.setText("Modificar Mesa...");
        menuMesa.add(itemModificarMesa);

        itemEliminarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        itemEliminarMesa.setText("Eliminar Mesa...");
        menuMesa.add(itemEliminarMesa);

        submenuMesa.setText("Reportes");

        itemListarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/list-icon.png"))); // NOI18N
        itemListarMesa.setText("Listar Todo...");
        submenuMesa.add(itemListarMesa);

        menuMesa.add(submenuMesa);

        BarraMenu.add(menuMesa);

        menuVoto.setText("Voto");

        itemAgregarVoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        itemAgregarVoto.setText("Agregar Voto...");
        menuVoto.add(itemAgregarVoto);

        itemBuscarVoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        itemBuscarVoto.setText("Buscar Voto...");
        menuVoto.add(itemBuscarVoto);

        itemModificarVoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        itemModificarVoto.setText("Modificar Voto...");
        menuVoto.add(itemModificarVoto);

        itemEliminarVoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        itemEliminarVoto.setText("Eliminar Voto...");
        menuVoto.add(itemEliminarVoto);

        submenuVoto.setText("Reportes");

        itemListarVoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/list-icon.png"))); // NOI18N
        itemListarVoto.setText("Listar Todo...");
        submenuVoto.add(itemListarVoto);

        menuVoto.add(submenuVoto);

        BarraMenu.add(menuVoto);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAgregarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarPartidoActionPerformed
        // TODO add your handling code here:
        VentanaPartido ventana = new VentanaPartido(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.habilitarBotones(true, true, false, false);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarPartidoActionPerformed

    private void itemBuscarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarPartidoActionPerformed
        VentanaPartido ventana = new VentanaPartido(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.habilitarBotones(false, true, true, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarPartidoActionPerformed

    private void itemModificarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarPartidoActionPerformed
        itemBuscarPartidoActionPerformed(evt);
    }//GEN-LAST:event_itemModificarPartidoActionPerformed

    private void itemEliminarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarPartidoActionPerformed
        itemBuscarPartidoActionPerformed(evt);
    }//GEN-LAST:event_itemEliminarPartidoActionPerformed

    private void itemAgregarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarComunaActionPerformed
        VentanaComuna ventana = new VentanaComuna(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.habilitarBotones(true, true, false, false);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarComunaActionPerformed
    
    private void itemBuscarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarComunaActionPerformed
        VentanaComuna ventana = new VentanaComuna(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.habilitarBotones(false, true, true, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarComunaActionPerformed

    private void itemModiificarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModiificarComunaActionPerformed
        itemBuscarComunaActionPerformed(evt);
    }//GEN-LAST:event_itemModiificarComunaActionPerformed

    private void itemEliminarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarComunaActionPerformed
        itemBuscarComunaActionPerformed(evt);
    }//GEN-LAST:event_itemEliminarComunaActionPerformed

    private void itemAgregarLocalVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarLocalVotacionActionPerformed
        VentanaLocalVotacion ventana = new VentanaLocalVotacion(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.habilitarBotones(true, true, false, false);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarLocalVotacionActionPerformed

    private void itemBuscarLocalVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarLocalVotacionActionPerformed
        VentanaLocalVotacion ventana = new VentanaLocalVotacion(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.habilitarBotones(false, true, true, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarLocalVotacionActionPerformed

    private void itemModificarLocalVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarLocalVotacionActionPerformed
        itemBuscarLocalVotacionActionPerformed(evt);
    }//GEN-LAST:event_itemModificarLocalVotacionActionPerformed

    private void itemEliminarLocalVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarLocalVotacionActionPerformed
        itemBuscarLocalVotacionActionPerformed(evt);
    }//GEN-LAST:event_itemEliminarLocalVotacionActionPerformed

    private void itemAgregarCiudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarCiudadanoActionPerformed
        VentanaCiudadano ventana = new VentanaCiudadano(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.habilitarBotones(true, true, false, false);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarCiudadanoActionPerformed

    private void itemBuscarCiudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarCiudadanoActionPerformed
        VentanaCiudadano ventana = new VentanaCiudadano(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.habilitarBotones(false, true, true, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarCiudadanoActionPerformed

    private void itemModificarCiudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarCiudadanoActionPerformed
        itemBuscarCiudadanoActionPerformed(evt);
    }//GEN-LAST:event_itemModificarCiudadanoActionPerformed

    private void itemEliminarCiudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarCiudadanoActionPerformed
        itemBuscarCiudadanoActionPerformed(evt);
    }//GEN-LAST:event_itemEliminarCiudadanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem itemAgregarApoderado;
    private javax.swing.JMenuItem itemAgregarCandidato;
    private javax.swing.JMenuItem itemAgregarCiudadano;
    private javax.swing.JMenuItem itemAgregarComuna;
    private javax.swing.JMenuItem itemAgregarLocalVotacion;
    private javax.swing.JMenuItem itemAgregarMesa;
    private javax.swing.JMenuItem itemAgregarPartido;
    private javax.swing.JMenuItem itemAgregarVocal;
    private javax.swing.JMenuItem itemAgregarVoto;
    private javax.swing.JMenuItem itemBuscarApoderado;
    private javax.swing.JMenuItem itemBuscarCandidato;
    private javax.swing.JMenuItem itemBuscarCiudadano;
    private javax.swing.JMenuItem itemBuscarComuna;
    private javax.swing.JMenuItem itemBuscarLocalVotacion;
    private javax.swing.JMenuItem itemBuscarMesa;
    private javax.swing.JMenuItem itemBuscarPartido;
    private javax.swing.JMenuItem itemBuscarVocal;
    private javax.swing.JMenuItem itemBuscarVoto;
    private javax.swing.JMenuItem itemEliminarApoderado;
    private javax.swing.JMenuItem itemEliminarCandidato;
    private javax.swing.JMenuItem itemEliminarCiudadano;
    private javax.swing.JMenuItem itemEliminarComuna;
    private javax.swing.JMenuItem itemEliminarLocalVotacion;
    private javax.swing.JMenuItem itemEliminarMesa;
    private javax.swing.JMenuItem itemEliminarPartido;
    private javax.swing.JMenuItem itemEliminarVocal;
    private javax.swing.JMenuItem itemEliminarVoto;
    private javax.swing.JMenuItem itemLIstarLocalVotacion;
    private javax.swing.JMenuItem itemListarApoderado;
    private javax.swing.JMenuItem itemListarCandidato;
    private javax.swing.JMenuItem itemListarCiudadano;
    private javax.swing.JMenuItem itemListarComuna;
    private javax.swing.JMenuItem itemListarMesa;
    private javax.swing.JMenuItem itemListarPartido;
    private javax.swing.JMenuItem itemListarVocal;
    private javax.swing.JMenuItem itemListarVoto;
    private javax.swing.JMenuItem itemModificarApoderado;
    private javax.swing.JMenuItem itemModificarCandidato;
    private javax.swing.JMenuItem itemModificarCiudadano;
    private javax.swing.JMenuItem itemModificarLocalVotacion;
    private javax.swing.JMenuItem itemModificarMesa;
    private javax.swing.JMenuItem itemModificarPartido;
    private javax.swing.JMenuItem itemModificarVocal;
    private javax.swing.JMenuItem itemModificarVoto;
    private javax.swing.JMenuItem itemModiificarComuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu menuApoderadoMesa;
    private javax.swing.JMenu menuCandidato;
    private javax.swing.JMenu menuCiudadano;
    private javax.swing.JMenu menuComuna;
    private javax.swing.JMenu menuLocalVotacion;
    private javax.swing.JMenu menuMesa;
    private javax.swing.JMenu menuPartido;
    private javax.swing.JMenu menuVocalMesa;
    private javax.swing.JMenu menuVoto;
    private javax.swing.JMenu submenuApoderado;
    private javax.swing.JMenu submenuCandidato;
    private javax.swing.JMenu submenuCiudadano;
    private javax.swing.JMenu submenuComuna;
    private javax.swing.JMenu submenuLocalVotacion;
    private javax.swing.JMenu submenuMesa;
    private javax.swing.JMenu submenuPartido;
    private javax.swing.JMenu submenuVocal;
    private javax.swing.JMenu submenuVoto;
    // End of variables declaration//GEN-END:variables
}
