package co.edu.ude.poo.procesospoliticos.vistas.gui;

import co.edu.ude.poo.procesospoliticos.modelo.entidades.Ciudadano;
import co.edu.ude.poo.procesospoliticos.modelo.entidades.Comuna;
import co.edu.ude.poo.procesospoliticos.modelo.entidades.LocalVotacion;
import co.edu.ude.poo.procesospoliticos.modelo.entidades.MesaVotacion;
import co.edu.ude.poo.procesospoliticos.modelo.crud.MesaVotacionCrud;
import co.edu.ude.poo.procesospoliticos.modelo.entidades.VocalMesa;
import co.edu.ude.poo.procesospoliticos.modelo.entidades.ApoderadoMesa;

import java.awt.Toolkit;

import javax.swing.JOptionPane;

/**
 * @author camilo castellar
 */
public class VentanaMesa extends javax.swing.JDialog {

    // instacia de clase CRUD mesa
    MesaVotacionCrud mesaVotacionCrud = new MesaVotacionCrud();
    
    public VentanaMesa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void habilitarBotones(boolean agregar, boolean buscar, boolean modificar, boolean eliminar) {
        btnAgregarMesa.setEnabled(agregar);
        btnBuscarMesa.setEnabled(buscar);
        btnModificarMesa.setEnabled(modificar);
        btnEliminarMesa.setEnabled(eliminar);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoGenero = new javax.swing.ButtonGroup();
        grupoEstadoMesa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroMesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLocalMesa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtVocalMesa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApoderadoUno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApoderadoDos = new javax.swing.JTextField();
        radioMujer = new javax.swing.JRadioButton();
        radioHombre = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        radioAbierta = new javax.swing.JRadioButton();
        radioCerrada = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarMesa = new javax.swing.JButton();
        btnBuscarMesa = new javax.swing.JButton();
        btnModificarMesa = new javax.swing.JButton();
        btnEliminarMesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procesos Politícos - Gestión de Mesas de Votación");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Datos de mesa de votación:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Numero de mesa:");

        txtNumeroMesa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtNumeroMesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroMesaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Local de votación:");

        txtLocalMesa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Vocal de mesa:");

        txtVocalMesa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Apoderado 1");

        txtApoderadoUno.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Apoderado 2");

        txtApoderadoDos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        grupoGenero.add(radioMujer);
        radioMujer.setText("MUJER");

        grupoGenero.add(radioHombre);
        radioHombre.setText("HOMBRE");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Genero:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Estado:");

        grupoEstadoMesa.add(radioAbierta);
        radioAbierta.setText("ABIERTA");

        grupoEstadoMesa.add(radioCerrada);
        radioCerrada.setText("CERRADA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLocalMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVocalMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtApoderadoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApoderadoDos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(radioHombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioMujer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(radioAbierta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioCerrada, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLocalMesa, txtNumeroMesa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVocalMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApoderadoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApoderadoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioHombre)
                    .addComponent(radioMujer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioAbierta)
                    .addComponent(radioCerrada))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtLocalMesa, txtNumeroMesa});

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO PARA GESTIONAR MESAS DE VOTACIÓN");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/Household-Table-icon.png"))); // NOI18N

        btnAgregarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/add-icon.png"))); // NOI18N
        btnAgregarMesa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAgregarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMesaActionPerformed(evt);
            }
        });

        btnBuscarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/search-icon.png"))); // NOI18N
        btnBuscarMesa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBuscarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMesaActionPerformed(evt);
            }
        });

        btnModificarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/edit-icon.png"))); // NOI18N
        btnModificarMesa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMesaActionPerformed(evt);
            }
        });

        btnEliminarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/procesospoliticos/vistas/iconos/delete-icon.png"))); // NOI18N
        btnEliminarMesa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMesaActionPerformed
        // Datos de formulario, crear un apoderado de mesa
        String numeroMesa = txtNumeroMesa.getText();

        // Validar que no este vacio el dni
        if (numeroMesa == null || numeroMesa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el numero de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNumeroMesa.setText("");
            txtNumeroMesa.requestFocus();
            return;
        }

        String localVotacion = txtLocalMesa.getText();
        
        // Validar que no este vacio el rol
        if (localVotacion == null || localVotacion.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el rol del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLocalMesa.setText("");
            txtLocalMesa.requestFocus();
            return;
        }
        
        String vocalMesa = txtVocalMesa.getText();

        // Validar que no este vacio el nombre
        if (vocalMesa == null || vocalMesa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el nombre del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtVocalMesa.setText("");
            txtVocalMesa.requestFocus();
            return;
        }

        String apoderadoUno = txtApoderadoUno.getText();

        // Validar que no este vacio el apellido

        if (apoderadoUno == null || apoderadoUno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el apellido del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtApoderadoUno.setText("");
            txtApoderadoUno.requestFocus();
            return;
        }

        String apoderadoDos = txtApoderadoDos.getText();

        // Validar que no este vacio el apellido

        if (apoderadoDos == null || apoderadoDos.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el apellido del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtApoderadoDos.setText("");
            txtApoderadoDos.requestFocus();
            return;
        }

        // validar los radio button
        String genero = "";

        if (radioHombre.isSelected()) {
            genero = "HOMBRE";
        } else if (radioMujer.isSelected()) {
            genero = "MUJER";
        }

        // validar los radio button no esten vacios

        if (genero == null || genero.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione el genero del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String estado = "";

        if (radioAbierta.isSelected()) {
            estado = "ABIERTA";
        } else if (radioCerrada.isSelected()) {
            estado = "CERRADA";
        }

        // validar los radio button no esten vacios

        if (estado == null || estado.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione el estado de la mesa de votación", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        // Con el objeto Ciudadano crea 3 personas
        Ciudadano ciudadano1 = new Ciudadano(100, 20, "Camilo Castellar", "HOMBRE");
        Ciudadano ciudadano2 = new Ciudadano(200, 30, "Juan Perez", "HOMBRE");
        Ciudadano ciudadano3 = new Ciudadano(300, 40, "Maria Perez", "MUJER");

        // crea un vocal de mesa
        VocalMesa vocalMesa1 = new VocalMesa(ciudadano1, "Presidente");

        // crea un apoderado de mesa
        ApoderadoMesa apoderadoMesa1 = new ApoderadoMesa(ciudadano2, 12345);
        ApoderadoMesa apoderadoMesa2 = new ApoderadoMesa(ciudadano3, 54321);
        
        // crea una comuna
        Comuna comuna = new Comuna("Cartagena");

        // crea un local de votacion
        LocalVotacion local = new LocalVotacion(comuna, localVotacion);

        // Crear un objeto de mesa de votacion
        MesaVotacion mesaVotacion = new MesaVotacion(Integer.parseInt(numeroMesa), genero, estado, local, vocalMesa1, apoderadoMesa1, apoderadoMesa2);

        try {
            mesaVotacionCrud.agregarMesaVotacion(Integer.parseInt(numeroMesa), mesaVotacion);
            JOptionPane.showMessageDialog(this, "La mesa de votación con número: " + numeroMesa + " se agrego con éxito", "RESULTADO", JOptionPane.WARNING_MESSAGE);
            txtNumeroMesa.setText("");
            txtLocalMesa.setText("");
            txtVocalMesa.setText("");
            txtApoderadoUno.setText("");
            txtApoderadoDos.setText("");
            grupoGenero.clearSelection();
            grupoEstadoMesa.clearSelection();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarMesaActionPerformed

    private void txtNumeroMesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroMesaKeyTyped
        // validar que el ID sea Integer
        char tecla = evt.getKeyChar();
        if(!Character.isDigit(tecla)) { 
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroMesaKeyTyped

    private void btnBuscarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMesaActionPerformed
        String numeroMesa = txtNumeroMesa.getText();

        // Validar que no este vacio el dni
        if (numeroMesa == null || numeroMesa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el numero de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNumeroMesa.setText("");
            txtNumeroMesa.requestFocus();
            return;
        }

        // validar que el contenga la llave a buscar
        if (!mesaVotacionCrud.mesas.containsKey(Integer.parseInt(numeroMesa))) {
            JOptionPane.showMessageDialog(this, "La mesa de votación con número: " + numeroMesa + " no existe", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // se recupera el objeto para mostrarlo en los campos del formulario
        MesaVotacion mesaVotacion = mesaVotacionCrud.mesas.get(Integer.parseInt(numeroMesa));
        txtLocalMesa.setText(mesaVotacion.getLocalVotacion().getLocalVotacion());
        String DNIVocal = mesaVotacion.getVocalMesa().getCiudadano().getDNICiudadano().toString();
        txtVocalMesa.setText(DNIVocal);
        String DNIapoderadoUno = mesaVotacion.getApoderadoMesaUno().getCiudadano().getDNICiudadano().toString();
        txtApoderadoUno.setText(DNIapoderadoUno);
        String DNIapoderadoDos = mesaVotacion.getApoderadoMesaDos().getCiudadano().getDNICiudadano().toString();
        txtApoderadoDos.setText(DNIapoderadoDos);
        
        if (mesaVotacion.getGeneroMesa().equals("HOMBRE")) {
            radioHombre.setSelected(true);
        } else if (mesaVotacion.getGeneroMesa().equals("MUJER")) {
            radioMujer.setSelected(true);
        }
        
        if (mesaVotacion.getEstadoMesa().equals("ABIERTA")) {
            radioAbierta.setSelected(true);
        } else if (mesaVotacion.getEstadoMesa().equals("CERRADA")) {
            radioCerrada.setSelected(true);
        }

        // habilitar botones, y deshabilitar el boton agregar
        habilitarBotones(false, true, true, true);
    }//GEN-LAST:event_btnBuscarMesaActionPerformed

    private void btnModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMesaActionPerformed
        String numeroMesa = txtNumeroMesa.getText();

        // Validar que no este vacio
        if (numeroMesa == null || numeroMesa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el dni del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNumeroMesa.setText("");
            txtNumeroMesa.requestFocus();
            return;
        }

        // validar que el contenga la llave a buscar
        if (!mesaVotacionCrud.mesas.containsKey(Integer.parseInt(numeroMesa))) {
            JOptionPane.showMessageDialog(this, "La mesa de votación con número: " + numeroMesa + " no existe", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Datos de formulario, modificar un apoderado de mesa

        String localMesa = txtLocalMesa.getText();

        // Validar que no este vacio el rol
        if (localMesa == null || localMesa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el rol del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLocalMesa.setText("");
            txtLocalMesa.requestFocus();
            return;
        }

        String vocalMesa = txtVocalMesa.getText();

        // Validar que no este vacio el nombre

        if (vocalMesa == null || vocalMesa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el nombre del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtVocalMesa.setText("");
            txtVocalMesa.requestFocus();
            return;
        }

        String apoderadoUno = txtApoderadoUno.getText();

        // Validar que no este vacio el apellido

        if (apoderadoUno == null || apoderadoUno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el apellido del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtApoderadoUno.setText("");
            txtApoderadoUno.requestFocus();
            return;
        }

        String apoderadoDos = txtApoderadoDos.getText();

        // Validar que no este vacio el apellido

        if (apoderadoDos == null || apoderadoDos.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el apellido del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtApoderadoDos.setText("");
            txtApoderadoDos.requestFocus();
            return;
        }

        // validar los radio button

        String genero = "";

        if (radioHombre.isSelected()) {
            genero = "HOMBRE";
        } else if (radioMujer.isSelected()) {
            genero = "MUJER";
        }

        // validar los radio button no esten vacios

        if (genero == null || genero.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione el genero del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String estado = "";

        if (radioAbierta.isSelected()) {
            estado = "ABIERTA";
        } else if (radioCerrada.isSelected()) {
            estado = "CERRADA";
        }

        // validar los radio button no esten vacios

        if (estado == null || estado.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione el estado de la mesa de votación", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }


        // Con el objeto Ciudadano crea 3 personas
        Ciudadano ciudadano1 = new Ciudadano(100, 20, "Camilo Castellar", "HOMBRE");
        Ciudadano ciudadano2 = new Ciudadano(200, 30, "Juan Perez", "HOMBRE");
        Ciudadano ciudadano3 = new Ciudadano(300, 40, "Maria Perez", "MUJER");

        // crea un vocal de mesa
        VocalMesa vocalMesa1 = new VocalMesa(ciudadano1, "Presidente");

        // crea un apoderado de mesa
        ApoderadoMesa apoderadoMesa1 = new ApoderadoMesa(ciudadano2, 12345);
        ApoderadoMesa apoderadoMesa2 = new ApoderadoMesa(ciudadano3, 54321);
        
        // crea una comuna
        Comuna comuna = new Comuna("Cartagena");

        // crea un local de votacion
        LocalVotacion local = new LocalVotacion(comuna, localMesa);

        try {
            mesaVotacionCrud.actualizarMesaVotacion(Integer.parseInt(numeroMesa), genero, estado, local, vocalMesa1, apoderadoMesa1, apoderadoMesa2);
            JOptionPane.showMessageDialog(this, "La mesa de votación con número: " + numeroMesa + " se modifico con éxito", "RESULTADO", JOptionPane.WARNING_MESSAGE);
            txtNumeroMesa.setText("");
            txtLocalMesa.setText("");
            txtVocalMesa.setText("");
            txtApoderadoUno.setText("");
            txtApoderadoDos.setText("");
            grupoGenero.clearSelection();
            grupoEstadoMesa.clearSelection();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnModificarMesaActionPerformed

    private void btnEliminarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMesaActionPerformed
        String numeroMesa = txtNumeroMesa.getText();

        // Validar que no este vacio el DNI
        if (numeroMesa == null || numeroMesa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el DNI del vocal de mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNumeroMesa.setText("");
            txtNumeroMesa.requestFocus();
            return;
        }

        // validar que el contenga la llave a buscar
        if (!mesaVotacionCrud.mesas.containsKey(Integer.parseInt(numeroMesa))) {
            JOptionPane.showMessageDialog(this, "La mesa de votación con número: " + numeroMesa + " no existe", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar la mesa: " + numeroMesa + "?", "CONFIRMACION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE); 
        
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                mesaVotacionCrud.eliminarMesaVotacion(Integer.parseInt(numeroMesa));
                JOptionPane.showMessageDialog(this, "La mesa de votación con número: " + numeroMesa + " se elimino con éxito", "RESULTADO", JOptionPane.WARNING_MESSAGE);
                txtNumeroMesa.setText("");
                txtLocalMesa.setText("");
                txtVocalMesa.setText("");
                txtApoderadoUno.setText("");
                txtApoderadoDos.setText("");
                grupoGenero.clearSelection();
                grupoEstadoMesa.clearSelection();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarMesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaMesa dialog = new VentanaMesa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMesa;
    private javax.swing.JButton btnBuscarMesa;
    private javax.swing.JButton btnEliminarMesa;
    private javax.swing.JButton btnModificarMesa;
    private javax.swing.ButtonGroup grupoEstadoMesa;
    private javax.swing.ButtonGroup grupoGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioAbierta;
    private javax.swing.JRadioButton radioCerrada;
    private javax.swing.JRadioButton radioHombre;
    private javax.swing.JRadioButton radioMujer;
    private javax.swing.JTextField txtApoderadoDos;
    private javax.swing.JTextField txtApoderadoUno;
    private javax.swing.JTextField txtLocalMesa;
    private javax.swing.JTextField txtNumeroMesa;
    private javax.swing.JTextField txtVocalMesa;
    // End of variables declaration//GEN-END:variables
}
